apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  selector:
    matchLabels:
      app: weather
  replicas: 1
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: grantjamespowell/weather:43e1f465e56b79ea15a34fbd231b08b167e39adf
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 5
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          envFrom:
          - configMapRef:
              name: weather
          ports:
            - containerPort: 80
